# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('currentLocation', models.CharField(max_length=30)),
                ('Time', models.TimeField()),
                ('destination', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currentLocation', models.TextField()),
                ('destination', models.TextField()),
                ('tel', models.IntegerField()),
                ('booked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tel', models.IntegerField(default=0)),
                ('permit', models.TextField()),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
