# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('currentLocation', models.CharField(max_length=30)),
                ('Time', models.TimeField()),
                ('destination', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tel', models.IntegerField(help_text='Contact phone number')),
                ('permit', models.TextField()),
                ('email', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=30)),
                ('platenbr', models.CharField(max_length=30)),
            ],
        ),
    ]
