# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tel', models.IntegerField(default=0)),
                ('permit', models.TextField()),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
