# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0002_remove_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
