# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0002_auto_20191120_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='platenbr',
            field=models.CharField(blank=True, null=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entries',
            name='tel',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='entries',
            name='user_id',
            field=models.CharField(blank=True, null=True, max_length=30),
            preserve_default=False,
        ),
    ]
