# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-22 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0002_auto_20191122_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
