# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0003_auto_20191121_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='platenbr',
            field=models.CharField(blank=True, null=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entries',
            name='tel',
            field=models.IntegerField(help_text='Contact phone number'),
        ),
        migrations.AlterField(
            model_name='entries',
            name='user_id',
            field=models.CharField(blank=True, null=True,max_length=30),
            preserve_default=False,
        ),
    ]
