# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0004_auto_20191121_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='tel',
            field=models.IntegerField(default=-1),
        ),
    ]
