# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0005_auto_20191121_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
